codecov:
  notify:
    require_ci_to_pass: no

coverage:
  status:

    patch:
      default:
        target: 80.0%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure

    project:
      default: false
      library:
        target: auto
        threshold: 0.5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
        paths:
          - "!deep_metadetection/tests/*"
          - "deep_metadetection/*"

      tests:
        target: 95.0%
        paths:
          - "deep_metadetection/tests/*"
          - "!deep_metadetection/*"
